# Generated by Django 5.0.1 on 2024-01-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tennissession',
            name='date',
            field=models.DateField(),
        ),
    ]
