# Generated by Django 5.0.1 on 2024-03-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_achievement_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/profile-pic-temp.png', upload_to='profile_pics/'),
        ),
    ]
