# Generated by Django 5.0.1 on 2024-03-08 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('video', 'Video'), ('article', 'Article')], max_length=20)),
                ('reference', models.URLField()),
                ('video_url', models.CharField(blank=True, max_length=20, null=True)),
                ('article_image', models.ImageField(blank=True, null=True, upload_to='article_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, choices=[('backhand', 'Backhand'), ('forehand', 'Forehand'), ('warm_up', 'Warm Up'), ('cool_down', 'Cool Down'), ('stretching', 'Stretching'), ('serve', 'Serve'), ('agility', 'Agility'), ('volley', 'Volley'), ('slice', 'Slice'), ('stamina', 'Stamina'), ('tnlp', 'TNLP'), ('other', 'Other')], related_name='related_tags', to='tennis.resource')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('heading', 'Heading'), ('paragraph', 'Paragraph'), ('image', 'Image'), ('bullet_points', 'Bullet Points')], max_length=15)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='article_images/')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_sections', to='tennis.resource')),
            ],
        ),
        migrations.CreateModel(
            name='TennisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('notes', models.TextField()),
                ('date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
