# Generated by Django 5.0.1 on 2024-03-08 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlesection',
            name='article',
        ),
        migrations.AddField(
            model_name='articlesection',
            name='resource',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='article_sections', to='tennis.resource'),
        ),
        migrations.AddField(
            model_name='resource',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='resources', to='tennis.articlesection'),
        ),
    ]
