# Generated by Django 5.0.1 on 2024-03-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0003_remove_resource_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('backhand', 'Backhand'), ('forehand', 'Forehand'), ('warm_up', 'Warm Up'), ('cool_down', 'Cool Down'), ('stretching', 'Stretching'), ('serve', 'Serve'), ('agility', 'Agility'), ('volley', 'Volley'), ('slice', 'Slice'), ('stamina', 'Stamina'), ('tnlp', 'TNLP'), ('other', 'Other')], max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='resource',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tennis.tag'),
        ),
    ]
