# Generated by Django 5.0.1 on 2024-03-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0005_alter_articlesection_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tennissession',
            name='category',
            field=models.CharField(choices=[('backhand', 'Backhand'), ('forehand', 'Forehand'), ('serve', 'Serve'), ('volley', 'Volley'), ('slice', 'Slice'), ('smash', 'Smash'), ('drop-shot', 'Drop shot'), ('agility', 'Agility'), ('stamina', 'Stamina'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
