# Generated by Django 5.0.1 on 2024-03-09 23:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0006_tennissession_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tennissession',
            name='user',
        ),
        migrations.AddField(
            model_name='tennissession',
            name='users',
            field=models.ManyToManyField(related_name='tennis_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
